print("Selamat datang pada git dan github!")
print("Ini merupakan commit pertama pada file ini!")
print("Halo nama saya Dzulfikri Adjmal lahir di Jakarta")
print("Halooo semuanya selamat pagi!")
print("Halo juga nama Adinda Rizky Sya'bana Diva dengan panggilan Banana!:v")
print("Saya sedang mencoba push menggunakan SSH")
print("Latihan menggunakan rebase")