print("Selamat datang pada git dan github!")
print("Ini merupakan commit pertama pada file ini!")
print("Halo nama saya Dzulfikri Adjmal lahir di Jakarta")
print("Halooo semuanya selamat pagi!")
print("Halo juga nama saya orang")
print("Saya sedang mencoba push menggunakan SSH")